[tool.poetry]
name = "doltcli"
version = "0.1.5"
description = "Slim Python interface for Dolt's CLI API."
authors = ["Max Hoffman <max@dolthub.com>", "Oscar Batori <oscar@dolthub.com>"]

[tool.poetry.dependencies]
python = "^3.6"
dataclasses = {version = ">=0.6", markers = "python_version < \"3.7\""}

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
black = "^20.8b1"
mypy = "0.800"
pytest-cov = "^2.11.1"

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
